[package]
name = "rust-minikeyvalue"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bytes = "1.7.1"
clap = { version = "4.5.17", features = ["derive"] }
env_logger = "0.11.5"
leveldb = "0.8.6"
log = "0.4.22"
tokio = { version = "1.40.0", features = ["full"] }
warp = "0.3.7"
